# Pipeline simple pour EduPlatform
# Pipeline minimaliste pour éviter les problèmes de parallelism

trigger:
- main

# Utilisation d'un agent auto-hébergé ou demande de grant
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to Artifact Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*.html
      **/*.css
      **/*.js
      !.git/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'website'
    publishLocation: 'Container'

- script: |
    echo "Build completed successfully!"
    echo "Website files are ready for deployment"
    echo "Request parallelism grant at: https://aka.ms/azpipelines-parallelism-request"
  displayName: 'Build Summary'
